name: Deploy a Surge

on:
  push:
    branches:
      - master

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repo
      uses: actions/checkout@v3

    - name: Install Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '16'

    - name: Install Surge
      run: npm install --global surge

    - name: Deploy to Surge
      env:
        SURGE_LOGIN: ${{ secrets.SURGE_LOGIN }}
        SURGE_TOKEN: ${{ secrets.SURGE_TOKEN }}
      run: surge ./ https://miwebfherdy.surge.sh --login $SURGE_LOGIN --token $SURGE_TOKEN
